name: Healthy
favicon: null
layout_spectrum: 0.34744
typography_spectrum: 0.2680419322568923
title: Staying Healthy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
